name: TeleportManager
version: 1.0.0
main: TeleportManager\Main
api: 5.0.0
author: Firekid846
description: Advanced teleport management system

commands:
  tp:
    description: Teleport to a player or teleport player1 to player2
    usage: "/tp <player> or /tp <player1> <player2>"
    permission: teleportmanager.tp
  tphere:
    description: Teleport a player to you
    usage: "/tphere <player>"
    permission: teleportmanager.tphere
  tpall:
    description: Teleport all players to you
    usage: "/tpall"
    permission: teleportmanager.tpall
  tppos:
    description: Teleport to coordinates
    usage: "/tppos <x> <y> <z> [world]"
    permission: teleportmanager.tppos
  tpworld:
    description: Teleport to a world's spawn
    usage: "/tpworld <world>"
    permission: teleportmanager.tpworld

permissions:
  teleportmanager.tp:
    description: Allows teleporting to players
    default: op
  teleportmanager.tphere:
    description: Allows teleporting players to you
    default: op
  teleportmanager.tpall:
    description: Allows teleporting all players to you
    default: op
  teleportmanager.tppos:
    description: Allows teleporting to coordinates
    default: op
  teleportmanager.tpworld:
    description: Allows teleporting to worlds
    default: op
